Importing the dependencies

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [6]:
#Loading data into pandas dataframe
data=pd.read_csv('/content/creditcard.csv')

In [7]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
data.shape

(53571, 31)

In [9]:
data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
53566,46047,-2.885416,-2.647887,1.903441,3.726885,3.800798,-1.644480,-1.924198,0.707696,-1.070468,...,0.284893,-0.268122,0.977417,0.136853,-1.144367,-0.535616,0.098494,0.305740,19.02,0.0
53567,46048,1.061410,0.045830,0.970401,1.102883,-0.490685,0.219968,-0.424285,0.235960,0.016498,...,0.033158,0.067127,0.053801,-0.010221,0.209877,-0.484136,0.057583,0.028018,28.70,0.0
53568,46048,-0.202740,0.295074,1.924698,1.009344,-0.235931,-0.272232,0.261015,-0.162146,-0.583849,...,0.321731,1.056540,0.093902,0.608566,-0.931546,0.466156,0.016695,-0.024568,54.81,0.0
53569,46048,-0.730116,0.796820,2.122484,-1.318082,0.019762,-0.857857,0.975752,-0.399896,0.359189,...,-0.149736,0.093479,-0.056586,0.650087,-0.473889,0.662115,0.060486,-0.208536,4.53,0.0
53570,46050,0.791672,-0.522991,0.036747,1.204803,-0.262390,-0.056153,0.263614,-0.130209,0.125423,...,0.013131,-0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#Dataset information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53571 entries, 0 to 53570
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    53571 non-null  int64
 1   V1      53571 non-null  float64
 2   V2      53571 non-null  float64
 3   V3      53571 non-null  float64
 4   V4      53571 non-null  float64
 5   V5      53571 non-null  float64
 6   V6      53571 non-null  float64
 7   V7      53571 non-null  float64
 8   V8      53571 non-null  float64
 9   V9      53571 non-null  float64
 10  V10     53571 non-null  float64
 11  V11     53571 non-null  float64
 12  V12     53571 non-null  float64
 13  V13     53571 non-null  float64
 14  V14     53571 non-null  float64
 15  V15     53571 non-null  float64
 16  V16     53571 non-null  float64
 17  V17     53571 non-null  float64
 18  V18     53571 non-null  float64
 19  V19     53571 non-null  float64
 20  V20     53571 non-null  float64
 21  V21     53571 non-null  float64
 22  V22     53571 non-null  float64
 23  V23     53570 non-null  float64
 24  V24     53570 non-null  float64
 25  V25     53570 non-null  float64
 26  V26     53570 non-null  float64
 27  V27     53570 non-null  float64
 28  V28     53570 non-null  float64
 29  Amount  53570 non-null  float64
 30  Class   53570 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 12.7 MB

In [11]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [12]:
data.dropna(inplace=True)

In [16]:
#checking the no.of fradulent and legit transactions
data['Class'].value_counts()

0.0    53417
1.0      153
Name: Class, dtype: int64

This data is highly imbalanced
  0---> Normal tranctions
  1---> Fradulent transactions

In [17]:
legit=data[data.Class==0]
fraud=data[data.Class==1]

In [18]:
legit.shape

(53417, 31)

In [19]:
fraud.shape

(153, 31)

In [20]:
#statistical methods of data
legit.Amount.describe()

count    53417.000000
mean        94.251260
std        252.353693
min          0.000000
25%          7.680000
50%         25.520000
75%         86.650000
max      12910.930000
Name: Amount, dtype: float64

In [21]:
fraud.Amount.describe()

count     153.000000
mean       97.616013
std       230.026856
min         0.000000
25%         1.000000
50%         7.610000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [23]:
#compare the values for both transactions
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,30011.81811,-0.222505,-0.014659,0.722511,0.163565,-0.242775,0.109604,-0.097131,0.042665,0.104805,...,0.046251,-0.031568,-0.106396,-0.038408,0.008094,0.134794,0.019825,0.002289,0.003902,94.251260
1.0,27472.24183,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

Under Sampling

No of fraud transactions = 153

In [24]:
legit_sample=legit.sample(n=180)

In [33]:
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49140,43928,0.933794,-1.798272,0.416834,-1.180051,-1.665376,-0.311882,-0.694073,-0.191270,-1.997960,...,-0.159268,-0.619940,-0.048540,0.082655,0.008369,-0.414673,0.017613,0.077095,285.70,0.0
42135,40968,-0.719695,1.032719,1.291331,-0.316841,0.223420,0.052549,0.463471,0.289385,-0.333485,...,-0.211255,-0.512044,-0.028615,-0.355922,-0.226207,0.111559,0.385136,0.159972,8.43,0.0
43099,41370,-0.766920,0.639693,1.178196,-1.193654,0.119951,-0.628108,0.742156,-0.196932,0.283874,...,-0.221850,-0.608049,0.207268,-0.048649,-1.062379,0.151404,-0.243300,0.053260,20.00,0.0
35183,38004,0.787610,-1.458338,-0.133339,-0.270909,-1.300042,-0.776237,0.015063,-0.198090,-0.997597,...,-0.216660,-0.747168,-0.239389,0.577739,0.245263,1.033495,-0.131732,0.038765,296.76,0.0
13607,24098,-0.502693,0.851534,0.992914,0.491266,0.656654,0.352736,0.530327,-0.202775,1.234209,...,-0.325728,-0.480220,-0.154856,-1.004888,-0.304983,0.286837,-0.130530,0.148985,34.14,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42373,41079,1.217494,0.634633,-0.470778,1.162565,0.263796,-0.741866,0.172700,-0.052714,-0.262441,...,-0.042598,-0.105520,-0.171390,-0.142038,0.690138,-0.323044,0.028163,0.043063,1.00,0.0
42812,41258,1.157116,-0.227916,1.122789,0.671485,-0.872917,0.213669,-0.731842,0.241341,0.694209,...,-0.060517,-0.020915,-0.024279,0.046264,0.267848,0.319370,0.012120,0.014212,11.49,0.0
34432,37664,1.582101,-1.197678,-1.147417,-2.504297,0.984772,3.234035,-1.492196,0.747692,-1.984488,...,-0.269321,-0.522610,0.001930,0.981586,0.549879,-0.190893,0.033277,0.013703,10.00,0.0
10459,17070,1.062401,-0.585550,0.585428,-0.616946,-0.744241,-0.198978,-0.448135,-0.181707,2.952508,...,0.026817,0.392650,-0.355528,-0.430744,0.718156,-0.536084,0.052914,0.043562,129.60,0.0
7162,9385,1.277324,0.020771,0.711620,0.906633,-0.302123,0.207496,-0.439748,-0.071859,2.192339,...,-0.344945,-0.346779,-0.158621,-0.409774,0.634101,0.538742,-0.025721,-0.000933,0.01,0.0

Concatening two datasets

In [29]:
final_data=pd.concat([legit_sample,fraud],axis=0)

In [30]:
final_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49140,43928,0.933794,-1.798272,0.416834,-1.180051,-1.665376,-0.311882,-0.694073,-0.191270,-1.997960,...,-0.159268,-0.619940,-0.048540,0.082655,0.008369,-0.414673,0.017613,0.077095,285.70,0.0
42135,40968,-0.719695,1.032719,1.291331,-0.316841,0.223420,0.052549,0.463471,0.289385,-0.333485,...,-0.211255,-0.512044,-0.028615,-0.355922,-0.226207,0.111559,0.385136,0.159972,8.43,0.0
43099,41370,-0.766920,0.639693,1.178196,-1.193654,0.119951,-0.628108,0.742156,-0.196932,0.283874,...,-0.221850,-0.608049,0.207268,-0.048649,-1.062379,0.151404,-0.243300,0.053260,20.00,0.0
35183,38004,0.787610,-1.458338,-0.133339,-0.270909,-1.300042,-0.776237,0.015063,-0.198090,-0.997597,...,-0.216660,-0.747168,-0.239389,0.577739,0.245263,1.033495,-0.131732,0.038765,296.76,0.0
13607,24098,-0.502693,0.851534,0.992914,0.491266,0.656654,0.352736,0.530327,-0.202775,1.234209,...,-0.325728,-0.480220,-0.154856,-1.004888,-0.304983,0.286837,-0.130530,0.148985,34.14,0.0

In [31]:
final_data.shape

(333, 31)

In [32]:
final_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28566.533333,-0.068410,0.060034,0.670854,0.142826,-0.268798,0.142845,-0.117487,-0.039550,0.241876,...,0.088034,0.009167,-0.172387,-0.049574,-0.105361,0.138646,-0.006141,0.013299,0.054026,95.440500
1.0,27472.241830,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

In [35]:
#splitting data into features and targets
x=final_data.drop(columns='Class',axis=1)
y=final_data['Class']

In [36]:
x.head(2)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
49140,43928,0.933794,-1.798272,0.416834,-1.180051,-1.665376,-0.311882,-0.694073,-0.191270,-1.997960,...,0.293769,-0.159268,-0.619940,-0.048540,0.082655,0.008369,-0.414673,0.017613,0.077095,285.70
42135,40968,-0.719695,1.032719,1.291331,-0.316841,0.223420,0.052549,0.463471,0.289385,-0.333485,...,0.163093,-0.211255,-0.512044,-0.028615,-0.355922,-0.226207,0.111559,0.385136,0.159972,8.43

In [37]:
y.head(3)

49140    0.0
42135    0.0
43099    0.0
Name: Class, dtype: float64

Splitting data into Training data  and testing data

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [41]:
x_train.shape

(266, 30)

Model Training

In [42]:
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [43]:
#Accuracy score of train data
x_pred=model.predict(x_train)
training_score=accuracy_score(x_pred,y_train)

In [44]:
print(f'training data accuracy score: {training_score}')

training data accuracy score: 0.9511278195488722

In [45]:
#Accuracy score of test data
y_pred=model.predict(x_test)
testing_score=accuracy_score(y_pred,y_test)

In [46]:
print(f'testing data accuracy score: {testing_score}')

testing data accuracy score: 0.9402985074626866